import { AlbumCoverPickerModal } from "./AlbumCoverPickerModal";

export const AlbumCreateModal = ({
    isOpen,
    onClose,
    onSubmit,
    isSaving,
    albumName,
    onAlbumNameChange,
    coverSearch,
    onCoverSearchChange,
    mediaViewMode,
    onMediaViewModeChange,
    mediaItems,
    filteredCoverCandidates,
    selectedCoverMediaId,
    onSelectCoverMedia,
    getAssetUrl,
    mapTagsFromMedia,
    selectedIncludeFilterTags,
    selectedExcludeFilterTags,
    onToggleIncludeFilterTag,
    onToggleExcludeFilterTag,
    onClearFilterTags,
    tagFilterSearch,
    onTagFilterSearchChange,
    visibleTagFilterCandidates,
    error,
}) => {
    return (
        <AlbumCoverPickerModal
            isOpen={isOpen}
            onClose={onClose}
            onSubmit={onSubmit}
            isSaving={isSaving}
            mode="create"
            albumName={albumName}
            onAlbumNameChange={onAlbumNameChange}
            coverSearch={coverSearch}
            onCoverSearchChange={onCoverSearchChange}
            mediaViewMode={mediaViewMode}
            onMediaViewModeChange={onMediaViewModeChange}
            mediaItems={mediaItems}
            filteredCoverCandidates={filteredCoverCandidates}
            selectedCoverMediaId={selectedCoverMediaId}
            onSelectCoverMedia={onSelectCoverMedia}
            getAssetUrl={getAssetUrl}
            mapTagsFromMedia={mapTagsFromMedia}
            selectedIncludeFilterTags={selectedIncludeFilterTags}
            selectedExcludeFilterTags={selectedExcludeFilterTags}
            onToggleIncludeFilterTag={onToggleIncludeFilterTag}
            onToggleExcludeFilterTag={onToggleExcludeFilterTag}
            onClearFilterTags={onClearFilterTags}
            tagFilterSearch={tagFilterSearch}
            onTagFilterSearchChange={onTagFilterSearchChange}
            visibleTagFilterCandidates={visibleTagFilterCandidates}
            error={error}
        />
    );
};
